---
- name: Import Wind River Root CA to Linux machine
  hosts: all
  tasks:
  - block:
    - name: Download rootCA.crt
      ansible.builtin.get_url:
        url: http://128.224.97.52/Config/rootCA.crt
        dest: /etc/pki/ca-trust/source/anchors/
        mode: '0755'
    - name: Run update-ca-trust extract
      ansible.builtin.shell: update-ca-trust extract
    when: ansible_distribution == 'Rocky' or ansible_distribution == 'CentOS' or ansible_distribution == 'RedHat'

  - block:
    - name: Install the package "ca-certificates"
      ansible.builtin.apt:
        name: ca-certificates

    - name: Download rootCA.crt
      ansible.builtin.get_url:
        url: http://128.224.97.52/Config/rootCA.crt
        dest: /usr/local/share/ca-certificates/
        mode: '0755'
    - name: Run update-ca-certificates
      ansible.builtin.shell: update-ca-certificates
    when: ansible_distribution == 'Ubuntu'
